[package]
name = "recipes"
version = "0.1.0"
authors = ["Piotr Tomczyk <p.tomczyk@binarapps.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
bytes = "*"
prost = "*"
reqwest = "*"
http = "0.1"
lambda_runtime = "*"
scraper = "*"
url = "*"
rand = "0.6.5"
now_lambda = "*"

[build-dependencies]
prost-build = { version = "*" }

[[bin]]
name = "get_recipe"
path = "src/bin/get_recipe.rs"

[[bin]]
name = "main"
path = "src/main.rs"